### ISSUE TITLE
Order of mixed args and kwargs breaks either Python 2 or 3

### ISSUE THREAD

**Issue by rmx90210** [CityOfPhiladelphia/datum#3]
Having mixed args and kwargs in this order doesn't work in Python 2:
`def create_index(self, *fields, name=None):`

Having them in this order works in Python 2, but breaks Python 3:
`def create_index(self, name=None, *fields):`
Specifically, `fields` is always an empty tuple.

@timwis I'm rolling this back to the old order as a quick fix for AIS, but there must be a solution for this somewhere.

**Comment by timwis** [comment]
I'm new to `*args` but is there a reason not to just make the `fields` argument a list? It looks you're [converting it](https://github.com/CityOfPhiladelphia/datum/blob/master/datum/postgis/table.py#L288) to one anyway.

**Comment by rmx90210** [comment]
We could do that. The `*args` look a little cleaner IMO, but I'm fine with just making it work :)

**Comment by rmx90210** [comment]
Actually, just realized that's going to break the AIS code. How about this workaround for now?

```
def create_index(self, *fields, **kwargs):
    name = kwargs.pop('name', None)
```
